-- Job Hunting with Sandy — Supabase schema
-- =========================================
-- Run this ONCE in your Supabase project: Dashboard -> SQL Editor -> New query ->
-- paste this whole file -> Run. Safe to re-run (uses "if not exists" / "or replace").
--
-- Design notes:
--   * Every row is owned by the logged-in user via user_id (defaults to auth.uid()).
--   * Row-Level Security ensures each account can only see and change its own rows.
--   * Date-like fields are stored as text to match the app, which uses "YYYY-MM-DD"
--     strings and empty strings ("") and compares them as strings.
--   * Ids are text and generated by the app (e.g. "job-<uuid>", "sophia-TT-001").

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

create table if not exists public.applications (
  id               text not null,
  user_id          uuid not null default auth.uid() references auth.users (id) on delete cascade,
  role             text not null default '',
  company          text not null default '',
  job_link         text not null default '',
  source           text not null default '',
  status           text not null default 'saved',
  location         text not null default '',
  salary           text not null default '',
  applied_date     text not null default '',
  next_action      text not null default '',
  next_action_date text not null default '',
  tags             text[] not null default '{}',
  cv_version       text not null default '',
  contact_id       text not null default '',
  description      text not null default '',
  notes            text not null default '',
  source_id        text not null default '',
  created_at       timestamptz not null default now(),
  primary key (user_id, id)
);

create table if not exists public.cvs (
  id              text not null,
  user_id         uuid not null default auth.uid() references auth.users (id) on delete cascade,
  name            text not null default '',
  focus           text not null default '',
  file_name       text not null default '',
  file_type       text not null default '',
  file_size       bigint not null default 0,
  has_stored_file boolean not null default false,
  storage_path    text not null default '',
  updated         text not null default '',
  notes           text not null default '',
  created_at      timestamptz not null default now(),
  primary key (user_id, id)
);

create table if not exists public.contacts (
  id           text not null,
  user_id      uuid not null default auth.uid() references auth.users (id) on delete cascade,
  name         text not null default '',
  company      text not null default '',
  role         text not null default '',
  link         text not null default '',
  last_contact text not null default '',
  next_date    text not null default '',
  notes        text not null default '',
  created_at   timestamptz not null default now(),
  primary key (user_id, id)
);

-- Helpful indexes for the per-user fetch + ordering.
create index if not exists applications_user_created_idx on public.applications (user_id, created_at);
create index if not exists cvs_user_created_idx          on public.cvs (user_id, created_at);
create index if not exists contacts_user_created_idx     on public.contacts (user_id, created_at);

-- ---------------------------------------------------------------------------
-- Row-Level Security: each user only ever touches their own rows.
-- ---------------------------------------------------------------------------

alter table public.applications enable row level security;
alter table public.cvs          enable row level security;
alter table public.contacts     enable row level security;

do $$
declare
  t text;
begin
  foreach t in array array['applications', 'cvs', 'contacts']
  loop
    execute format('drop policy if exists "own rows select" on public.%I', t);
    execute format('drop policy if exists "own rows insert" on public.%I', t);
    execute format('drop policy if exists "own rows update" on public.%I', t);
    execute format('drop policy if exists "own rows delete" on public.%I', t);

    execute format(
      'create policy "own rows select" on public.%I for select using (auth.uid() = user_id)', t);
    execute format(
      'create policy "own rows insert" on public.%I for insert with check (auth.uid() = user_id)', t);
    execute format(
      'create policy "own rows update" on public.%I for update using (auth.uid() = user_id) with check (auth.uid() = user_id)', t);
    execute format(
      'create policy "own rows delete" on public.%I for delete using (auth.uid() = user_id)', t);
  end loop;
end $$;

-- ---------------------------------------------------------------------------
-- Storage: private bucket for CV files. Objects live under "<user_id>/<cv_id>".
-- ---------------------------------------------------------------------------

insert into storage.buckets (id, name, public)
values ('cv-files', 'cv-files', false)
on conflict (id) do nothing;

drop policy if exists "cv files select own" on storage.objects;
drop policy if exists "cv files insert own" on storage.objects;
drop policy if exists "cv files update own" on storage.objects;
drop policy if exists "cv files delete own" on storage.objects;

-- The first path segment must equal the user's id (auth.uid()).
create policy "cv files select own" on storage.objects
  for select using (
    bucket_id = 'cv-files' and (storage.foldername(name))[1] = auth.uid()::text);

create policy "cv files insert own" on storage.objects
  for insert with check (
    bucket_id = 'cv-files' and (storage.foldername(name))[1] = auth.uid()::text);

create policy "cv files update own" on storage.objects
  for update using (
    bucket_id = 'cv-files' and (storage.foldername(name))[1] = auth.uid()::text);

create policy "cv files delete own" on storage.objects
  for delete using (
    bucket_id = 'cv-files' and (storage.foldername(name))[1] = auth.uid()::text);
