window.SOPHIA_PIPELINE_VERSION = "2026-07-11-priority-tags";
window.SOPHIA_PIPELINE = [
  {
    Job_ID: "TT-001",
    Priority: "C - Low strategic fit",
    Status: "Researching",
    Company: "Turner & Townsend",
    Role_Title: "Associate Project Manager",
    Role_Family: "Infrastructure Project Management",
    Seniority: "Associate / experienced Project Manager",
    Location: "Edinburgh",
    Country: "United Kingdom",
    Work_Model: "Flexible working stated; exact hybrid pattern not specified",
    Job_Link: "https://jobs.smartrecruiters.com/TurnerTownsend/744000129160520-associate-project-manager",
    Source: "SmartRecruiters / Turner & Townsend",
    Date_Found: "2026-07-10",
    Application_Deadline: "",
    Salary: "Not stated",
    Visa_Sponsorship: "Not stated",
    Relocation_Support: "Not stated",
    Japanese_Requirement: "None stated",
    Key_Requirements: "Lead end-to-end project delivery; client interface; governance; master planning; resource and procurement planning; KPI and change control; budgets and forecasts; risk management; formal reporting. Ideally Civil Engineering degree, GBP100m+ scheme experience, NEC ECC Project Manager accreditation, and ICE/APM/RICS chartership.",
    Match_Evidence: "BlackRock project and release coordination; PaCT release planning; cloud migration lead; cross-functional stakeholder communication; requirements and UX workshops; Azure DevOps tracking; risk/issue coordination; production delivery and post-release accountability.",
    Skill_Gaps: "No demonstrated civil-engineering or capital-infrastructure background; no GBP100m+ scheme delivery; no NEC ECC accreditation; no ICE/APM/RICS chartership; limited evidence of construction procurement, capital-cost control, H&S or environmental project duties.",
    Match_Score_10: "4",
    Interest_Score_10: "7 - provisional",
    Visa_Feasibility_10: "Not assessed",
    Urgency_Score_10: "5",
    Application_Effort_5: "5",
    Strategic_Score_100: "45 - provisional",
    CV_Version: "Project Delivery / Technical PM pivot",
    Cover_Letter_Status: "Essential if applying",
    Referral_or_Contact: "",
    Networking_Status: "Search for an Edinburgh Turner & Townsend contact before applying",
    Applied_Date: "",
    Follow_Up_Date: "",
    Interview_Stage: "",
    Next_Action: "Treat as a stretch role. Apply only with a strong sector-transition narrative or referral; otherwise prioritise technology, digital transformation, product or programme roles.",
    Next_Action_Due: "2026-07-12",
    Outcome: "",
    Notes: "The title sounds broadly transferable, but the qualification section is strongly oriented toward civil infrastructure and major capital schemes."
  },
  {
    Job_ID: "MSI-001",
    Priority: "A - Apply now",
    Status: "Ready to Apply",
    Company: "Motorola Solutions",
    Role_Title: "Technical Project Manager",
    Role_Family: "Technical Project / Software Implementation",
    Seniority: "Experienced / Mid-Senior",
    Location: "Glasgow listing; primarily remote with travel to offices/customer sites",
    Country: "United Kingdom",
    Work_Model: "Primarily remote; 10-25% travel",
    Job_Link: "https://motorolasolutions.wd5.myworkdayjobs.com/en-US/Careers/job/Glasgow-UK-ZUK118/Technical-Project-Manager_R65418",
    Source: "Motorola Solutions Workday / LinkedIn",
    Date_Found: "2026-07-10",
    Application_Deadline: "Not stated",
    Salary: "Competitive; exact range not stated",
    Visa_Sponsorship: "Not stated",
    Relocation_Support: "None",
    Japanese_Requirement: "None stated",
    Key_Requirements: "Own delivery of complex Guardian Mobile software deployments; act as primary customer contact; capture business and technical requirements; produce solution specifications and resourced plans; manage development, testing, deployment and customer sign-off; maintain RAID logs, RFCs, contract changes and finance documentation; lead agile virtual delivery teams. Computing degree or equivalent experience, strong technical communication and complex software delivery experience required.",
    Match_Evidence: "Six years delivering regulated financial software; acted as Product Owner; requirements gathering and technical design; cross-functional translation between operations and engineering; PaCT release and cut-over ownership; cloud migration leadership; Azure DevOps tracking; development, testing, deployment, monitoring and post-release issue resolution; Java/Angular/API/database technical depth.",
    Skill_Gaps: "Limited evidence of external customer delivery and formal ownership of project finance/contract changes; no Fire & Rescue control-room or MDT domain experience; Agile certification should be made explicit if held.",
    Match_Score_10: "8.5",
    Interest_Score_10: "8 - provisional",
    Visa_Feasibility_10: "9 - subject to current UK work status",
    Urgency_Score_10: "9",
    Application_Effort_5: "4",
    Strategic_Score_100: "85",
    CV_Version: "Technical Project Manager / Software Deployment",
    Cover_Letter_Status: "Recommended",
    Referral_or_Contact: "Katy Bradley - UK Talent Acquisition Lead",
    Networking_Status: "Send a concise recruiter message after applying",
    Applied_Date: "",
    Follow_Up_Date: "",
    Interview_Stage: "",
    Next_Action: "Tailor CV around requirements -> solution design -> plan -> development/testing -> deployment/sign-off. Apply first, then message the named recruiter with a three-line evidence summary.",
    Next_Action_Due: "2026-07-11",
    Outcome: "",
    Notes: "Best fit so far. The role is essentially the bridge between customer operations and technical delivery - very close to Sophia's strongest product-owner/software-engineer combination."
  },
  {
    Job_ID: "RSG-001",
    Priority: "A - Apply",
    Status: "Ready to Apply",
    Company: "Rockstar Games",
    Role_Title: "Project Manager",
    Role_Family: "IT / Security Project Management",
    Seniority: "Experienced; 3+ years project management requested",
    Location: "Edinburgh",
    Country: "United Kingdom",
    Work_Model: "In-office",
    Job_Link: "https://job-boards.greenhouse.io/rockstargames/jobs/7738027003",
    Source: "Rockstar Games Greenhouse",
    Date_Found: "2026-07-10",
    Application_Deadline: "Not stated",
    Salary: "Not stated",
    Visa_Sponsorship: "Not stated; application asks for UK work eligibility",
    Relocation_Support: "Not stated",
    Japanese_Requirement: "None stated",
    Key_Requirements: "Coordinate cross-functional IT and Security initiatives; clarify requirements and feasibility; plan and prioritise execution; manage risks through communication and escalation; build relationships with technical teams; 3+ years project management, strong IT/Security understanding, leadership, ownership, project-management tools and excellent communication.",
    Match_Evidence: "Edinburgh-based software engineer and acting Product Owner; cross-functional delivery across Finance, Treasury, Operations, UX and Engineering; release and cloud migration leadership; requirements, planning, risk and dependency management; Azure DevOps; technical workshops; production incident and security/permission-control experience; strong knowledge of software delivery.",
    Skill_Gaps: "No formal Project Manager title and limited dedicated cybersecurity-domain evidence; degree is not in Computer Science/IT, so equivalent technical experience must be positioned clearly; PMP/CISSP/CISM absent.",
    Match_Score_10: "7.8",
    Interest_Score_10: "9 - provisional",
    Visa_Feasibility_10: "9 - subject to current UK work status",
    Urgency_Score_10: "8",
    Application_Effort_5: "5",
    Strategic_Score_100: "80",
    CV_Version: "IT Project Manager / Cross-Functional Delivery",
    Cover_Letter_Status: "Required by posting",
    Referral_or_Contact: "",
    Networking_Status: "Search for an Edinburgh IT/Security or Production contact",
    Applied_Date: "",
    Follow_Up_Date: "",
    Interview_Stage: "",
    Next_Action: "Prepare a focused CV and cover letter proving 3+ years of project-management responsibilities through PaCT, cloud migration, releases, UX initiatives and stakeholder coordination. Address security experience through permissions, controls, production resilience and regulated systems without exaggerating.",
    Next_Action_Due: "2026-07-12",
    Outcome: "",
    Notes: "Strong local opportunity and good cultural interest, but this is an IT/Security delivery role rather than game-production management. The cover letter will materially affect screening."
  },
  {
    Job_ID: "RSG-002",
    Priority: "A+ - Apply first",
    Status: "Ready to Apply",
    Company: "Rockstar Games",
    Role_Title: "Project Manager: Game Security",
    Role_Family: "Technical Project Management / Game Security",
    Seniority: "Experienced; 3+ years PM or multidisciplinary coordination",
    Location: "Edinburgh",
    Country: "United Kingdom",
    Work_Model: "In-office",
    Job_Link: "https://job-boards.greenhouse.io/rockstargames/jobs/7797781003",
    Source: "Rockstar Games Greenhouse",
    Date_Found: "2026-07-10",
    Application_Deadline: "Not stated",
    Salary: "Not stated",
    Visa_Sponsorship: "Not stated; application asks for UK work eligibility",
    Relocation_Support: "Not stated",
    Japanese_Requirement: "None stated",
    Key_Requirements: "Lead cross-functional Game Security initiatives; coordinate priorities, dependencies and delivery; facilitate Agile ceremonies and planning; manage plans, risks, blockers and milestones; balance strategic and operational work; stakeholder reporting; continuous improvement; 3+ years in project management or multidisciplinary team coordination; complex technical/operational delivery; Azure DevOps/Jira/Monday.com.",
    Match_Evidence: "Six years in regulated financial technology; acting Product Owner; coordinated Finance, Treasury, Operations, UX and Engineering; led Agile ceremonies, backlog refinement, release planning and cloud-migration testing; managed dependencies, blockers, production risks and stakeholder updates; Azure DevOps; technical depth in Java, Angular, APIs, data, permissions, validation and operational resilience.",
    Skill_Gaps: "No direct game-security, anti-cheat, fraud or Trust & Safety experience; no formal Agile certification stated; limited direct live-service gaming delivery. These are listed as desirable rather than mandatory.",
    Match_Score_10: "9.0",
    Interest_Score_10: "9.5 - provisional",
    Visa_Feasibility_10: "9 - subject to current UK work status",
    Urgency_Score_10: "9",
    Application_Effort_5: "4",
    Strategic_Score_100: "90",
    CV_Version: "Technical Project Manager / Agile Delivery",
    Cover_Letter_Status: "Essential; explicitly requested",
    Referral_or_Contact: "",
    Networking_Status: "Search for Edinburgh Game Security, Production or Technical PM contacts",
    Applied_Date: "",
    Follow_Up_Date: "",
    Interview_Stage: "",
    Next_Action: "Apply before the earlier Rockstar Project Manager role. Tailor CV around cross-functional delivery, Agile facilitation, risk/blocker management, operational resilience and security-adjacent controls. Write a cover letter translating regulated-finance delivery into player/game/IP protection without claiming direct game-security experience.",
    Next_Action_Due: "2026-07-11",
    Outcome: "",
    Notes: "Strongest Rockstar fit. The alternative requirement - project management OR multidisciplinary coordination - removes much of the title-risk. Game-security experience is only a plus."
  },
  {
    Job_ID: "HMRC-ADM-001",
    Priority: "Closed / archive",
    Status: "Deadline passed or closing imminently",
    Company: "HM Revenue & Customs",
    Role_Title: "Agile Delivery Manager",
    Role_Family: "Agile Delivery / Digital Delivery Management",
    Seniority: "SEO",
    Location: "Edinburgh (also Bristol, Leeds, Newcastle, Stratford, Telford, Worthing)",
    Country: "United Kingdom",
    Work_Model: "Hybrid; HMRC normally requires 60% office attendance",
    Job_Link: "https://www.civilservicejobs.service.gov.uk/csr/jobs.cgi?jcode=2003183",
    Source: "Civil Service Jobs / HMRC",
    Date_Found: "2026-07-10",
    Application_Deadline: "2026-07-10 23:55 UK time",
    Salary: "GBP45,544-GBP49,523 national; external applicants join at band minimum",
    Visa_Sponsorship: "No Skilled Worker sponsorship",
    Relocation_Support: "Not stated",
    Japanese_Requirement: "None",
    Key_Requirements: "Deliver medium-large digital products; proven Agile delivery management; coach and motivate multidisciplinary teams; forecast progress; remove blockers; balance high-visibility priorities; influence stakeholders; negotiate outcomes; support continuous improvement.",
    Match_Evidence: "Led PaCT releases and cloud-migration testing; ran sprint planning, backlog refinement and retrospectives; coordinated Finance, Treasury, Operations, UX and Engineering; tracked blockers and dependencies in Azure DevOps; managed production delivery and stakeholder updates; created collaborative team practices.",
    Skill_Gaps: "Formal Agile Delivery Manager title absent; limited explicit commercial/supplier and budget management evidence; coaching teams in Agile must be evidenced with concrete examples rather than ceremony participation alone.",
    Match_Score_10: "8.3",
    Interest_Score_10: "8 - provisional",
    Visa_Feasibility_10: "9 - if no sponsorship required",
    Urgency_Score_10: "0 - deadline passed/closing",
    Application_Effort_5: "5",
    Strategic_Score_100: "82 fit; 0 current opportunity due to deadline",
    CV_Version: "Agile Delivery Manager / Digital Delivery",
    Cover_Letter_Status: "750-word personal statement required",
    Referral_or_Contact: "Chloe Lambourne - chloe.lambourne@hmrc.gov.uk",
    Networking_Status: "Archive and watch for relisting or reserve-list campaigns",
    Applied_Date: "",
    Follow_Up_Date: "",
    Interview_Stage: "",
    Next_Action: "Do not spend application time unless the form is still open and already substantially complete. Reuse this role as a search template for future HMRC Agile Delivery Manager vacancies.",
    Next_Action_Due: "",
    Outcome: "",
    Notes: "Strong substantive fit, but the vacancy closed at the end of 10 July 2026. Application required a name-blind CV covering the last five roles and a 750-word personal statement; interview included a technical presentation."
  },
  {
    Job_ID: "HMRC-APM-001",
    Priority: "A+ - Apply first",
    Status: "Ready to Apply",
    Company: "HM Revenue & Customs",
    Role_Title: "Associate Product Manager",
    Role_Family: "Digital Product Management",
    Seniority: "SEO / entry-level product management",
    Location: "Edinburgh (also Leeds, Manchester, Newcastle-upon-Tyne, Worthing)",
    Country: "United Kingdom",
    Work_Model: "Hybrid; 60% office attendance",
    Job_Link: "https://www.civilservicejobs.service.gov.uk/csr/jobs.cgi?jcode=2002592",
    Source: "Civil Service Jobs / HMRC",
    Date_Found: "2026-07-10",
    Application_Deadline: "2026-07-13 23:55 UK time",
    Salary: "GBP45,544-GBP49,523",
    Visa_Sponsorship: "No Skilled Worker sponsorship",
    Relocation_Support: "Not stated",
    Japanese_Requirement: "None",
    Key_Requirements: "Define vision, scope and features for a product increment; deliver features through discovery, build and live; engage stakeholders; collaborate with multidisciplinary teams; apply user insight; maintain roadmap and backlog; prioritise by user need, value, risk and dependencies.",
    Match_Evidence: "Acting Product Owner at BlackRock; defined requirements, PRDs/specifications and MVPs; maintained backlogs and user stories; led UX reviews and user-feedback surveys; coordinated Finance, Treasury, Operations, UX and Engineering; delivered PaCT features and releases; strong software-engineering knowledge; direct experience in complex financial and data services.",
    Skill_Gaps: "Need to express product outcomes and measurable value more explicitly; formal roadmap ownership may be partial rather than sole; must avoid framing experience primarily as engineering delivery.",
    Match_Score_10: "9.5",
    Interest_Score_10: "9 - provisional",
    Visa_Feasibility_10: "9 - if no sponsorship required",
    Urgency_Score_10: "10",
    Application_Effort_5: "5",
    Strategic_Score_100: "94",
    CV_Version: "Associate Product Manager / Technical Product Owner",
    Cover_Letter_Status: "500-word personal statement required; optional 250-word desirable-criteria statement",
    Referral_or_Contact: "Garnedd Rowlands - garnedd.ifans.rowlands@hmrc.gov.uk",
    Networking_Status: "Optional; application quality matters more than cold outreach",
    Applied_Date: "",
    Follow_Up_Date: "",
    Interview_Stage: "",
    Next_Action: "Make this the next application. Build a name-blind Civil Service CV covering the last 3 roles (maximum 100 words each), then write a 500-word statement mapped tightly to the six essential criteria. Use PaCT, cloud migration, UX survey and payment-workflow examples.",
    Next_Action_Due: "2026-07-12",
    Outcome: "",
    Notes: "Best fit in the tracker. The role is explicitly entry-level product management, while financial, data, digital-service and software-engineering exposure are desirable. Initial sift may be based on the personal statement."
  },
  {
    Job_ID: "FCA-AIBA-001",
    Priority: "A+ - Apply immediately",
    Status: "Ready to Apply",
    Company: "Financial Conduct Authority",
    Role_Title: "Business Analyst - AI Product Development",
    Role_Family: "Business Analysis / AI Product Development / Regulatory Technology",
    Seniority: "Senior Associate - Regulatory",
    Location: "Edinburgh, Leeds or London",
    Country: "United Kingdom",
    Work_Model: "Hybrid; minimum 40% office attendance, increasing to 50% from September 2026",
    Job_Link: "https://fca.wd3.myworkdayjobs.com/en-US/FCA_Careers/job/London/Business-Analyst---AI-Product-Development_JR0021851-1",
    Source: "FCA Workday / Women in Data / Indeed",
    Date_Found: "2026-07-11",
    Application_Deadline: "2026-07-19 23:59 UK time",
    Salary: "GBP53,800-GBP72,000 Edinburgh/Leeds; GBP59,200-GBP80,000 London",
    Visa_Sponsorship: "Not specified for this vacancy; verify during application",
    Relocation_Support: "Not stated",
    Japanese_Requirement: "None",
    Key_Requirements: "Identify high-value AI opportunities; facilitate discovery workshops; map user journeys and business processes; translate problems into functional and non-functional requirements; prioritise an organisation-wide AI pipeline; work with data scientists and leadership; support AI adoption strategy. Requires senior BA or comparable Product Owner experience, full-lifecycle Agile and waterfall delivery, knowledge of LLMs/agentic AI/prompt engineering, requirements gathering, workshop facilitation, stakeholder management and complex problem solving.",
    Match_Evidence: "Acting Product Owner and software engineer in regulated financial services; requirements gathering, PRDs/specifications, user journeys, UX reviews and collaborative workshops; payment and approval process mapping; full lifecycle development, testing, release and production support; backlog and priority management; stakeholder relationships across Finance, Treasury, Operations, UX and Engineering; SQL/data experience; AI-assisted development using Copilot and lightweight agents.",
    Skill_Gaps: "Need stronger concrete examples of applied AI discovery and measurable AI outcomes; waterfall delivery should be described through structured release, migration and cut-over work; avoid overstating data-science or model-development expertise.",
    Match_Score_10: "9.6",
    Interest_Score_10: "9.5 - provisional",
    Visa_Feasibility_10: "8 - sponsorship not specified",
    Urgency_Score_10: "10",
    Application_Effort_5: "5",
    Strategic_Score_100: "96",
    CV_Version: "Senior Business Analyst / AI Product Development / RegTech",
    Cover_Letter_Status: "Application documents not fully specified; tailored CV essential",
    Referral_or_Contact: "Benjamin Paulon - benjamin.paulon@fca.org.uk",
    Networking_Status: "Apply through portal; recruiter contact is for process questions, not email applications",
    Applied_Date: "",
    Follow_Up_Date: "",
    Interview_Stage: "",
    Next_Action: "Make this a top-two application. Reframe BlackRock work as business analysis: discovery, process mapping, requirements, prioritisation, workshops and measurable operational outcomes. Prepare one AI example showing problem, user need, proposed workflow, risks, human oversight and expected value.",
    Next_Action_Due: "2026-07-13",
    Outcome: "",
    Notes: "Exceptional environment and capability fit: financial regulation, data, technology, AI opportunity shaping and Product Owner experience are all directly recognised. CV review is scheduled for 21 July; first interviews week commencing 27 July and second interviews week commencing 3 August."
  },
  {
    Job_ID: "CRB-PO-001",
    Priority: "A+ - Apply immediately",
    Status: "Ready to Apply",
    Company: "CRB Cunninghams / Vesta Software Group",
    Role_Title: "Product Owner",
    Role_Family: "Product Ownership / B2B SaaS / Payments & Operational Workflows",
    Seniority: "Experienced individual contributor",
    Location: "Remote UK; offices in Loanhead, Edinburgh and Headley, Birmingham",
    Country: "United Kingdom",
    Work_Model: "Remote",
    Job_Link: "https://talentmanagementsolution.wd3.myworkdayjobs.com/en-US/VestaUK/job/Product-Owner_R52171",
    Source: "Vesta Software Group Workday / CRB Cunninghams",
    Date_Found: "2026-07-11",
    Application_Deadline: "Not stated",
    Salary: "Not stated",
    Visa_Sponsorship: "Not stated",
    Relocation_Support: "Not applicable / not stated",
    Japanese_Requirement: "None",
    Key_Requirements: "Lead discovery and validation for an early-stage product opportunity; work with customers to define problems, users, value proposition and success criteria; shape roadmap and backlog; define hypotheses and MVP increments; partner with design and engineering through launch; measure adoption and traction; use AI effectively in product practice.",
    Match_Evidence: "Acting Product Owner plus software engineer; payments and approval workflows; PRDs, MVP definition, backlog and stakeholder management; UX research/surveys and design; operational workflow optimisation; regulated complexity; B2B internal platforms; ability to work directly with engineering from discovery through release.",
    Skill_Gaps: "Need stronger evidence of direct external-customer discovery, product-market-fit validation, commercial opportunity sizing and launching a wholly new market-facing product. Catering/kitchen workflow knowledge is absent but only desirable.",
    Match_Score_10: "9.3",
    Interest_Score_10: "9 - provisional",
    Visa_Feasibility_10: "8 - not stated",
    Urgency_Score_10: "9",
    Application_Effort_5: "4",
    Strategic_Score_100: "93",
    CV_Version: "Product Owner / Payments, UX & Operational Workflows",
    Cover_Letter_Status: "Strongly recommended",
    Referral_or_Contact: "careers@jonas-group.co.uk",
    Networking_Status: "Apply first; then seek a CRB/Jonas product contact",
    Applied_Date: "",
    Follow_Up_Date: "",
    Interview_Stage: "",
    Next_Action: "Apply directly after HMRC. Build the application around payment workflows, user discovery, smallest valuable increment, UX evidence, operational complexity and the advantage of being a Product Owner who can speak engineering fluently.",
    Next_Action_Due: "2026-07-12",
    Outcome: "",
    Notes: "Exceptionally strong wording match: payments, operational workflow products, B2B software and regulated complexity are all desirable."
  },
  {
    Job_ID: "NWG-ITAM-001",
    Priority: "A-/B+ - Verify then apply",
    Status: "Researching - assessment provisional",
    Company: "NatWest Group",
    Role_Title: "Product Owner, IT Asset Management",
    Role_Family: "Product Ownership / IT Service & Asset Management",
    Seniority: "Experienced; exact grade not confirmed",
    Location: "Edinburgh",
    Country: "United Kingdom",
    Work_Model: "Likely hybrid; confirm on application page",
    Job_Link: "https://www.efinancialcareers.co.uk/jobs-United_Kingdom-Edinburgh-Product_Owner_IT_Asset_Management.id24498187",
    Source: "eFinancialCareers / NatWest Group",
    Date_Found: "2026-07-11",
    Application_Deadline: "Not visible on accessible listing",
    Salary: "Competitive; exact range not visible",
    Visa_Sponsorship: "Not stated",
    Relocation_Support: "Not stated",
    Japanese_Requirement: "None",
    Key_Requirements: "Available listing confirms an Edinburgh Product Owner role shaping NatWest's future IT Asset Management capability. Detailed criteria were blocked by the third-party page; likely focus areas include product direction, backlog, stakeholder alignment and IT asset/service lifecycle outcomes.",
    Match_Evidence: "Product Owner responsibilities in a major regulated financial institution; software-engineering credibility; cloud migration, production releases, operational resilience, ServiceNow exposure, data quality and cross-functional stakeholder delivery.",
    Skill_Gaps: "IT Asset Management is not investment management. Dedicated evidence in CMDB, hardware/software lifecycle, licensing, vendor management, ServiceNow ITAM/SAM/HAM and asset governance is not currently strong.",
    Match_Score_10: "8.0 - provisional",
    Interest_Score_10: "8.5 - provisional",
    Visa_Feasibility_10: "8 - not stated",
    Urgency_Score_10: "8",
    Application_Effort_5: "4",
    Strategic_Score_100: "84 - provisional",
    CV_Version: "Technical Product Owner / IT Operations & Controls",
    Cover_Letter_Status: "Confirm application requirements",
    Referral_or_Contact: "",
    Networking_Status: "Check NatWest contacts before submission",
    Applied_Date: "",
    Follow_Up_Date: "",
    Interview_Stage: "",
    Next_Action: "Open the NatWest application and confirm the essential criteria. Apply if ITAM platform knowledge is desirable or learnable; downgrade immediately if several years of ServiceNow ITAM/CMDB ownership are mandatory.",
    Next_Action_Due: "2026-07-12",
    Outcome: "",
    Notes: "High environmental and title fit, but the detailed source page was inaccessible, so this score must remain provisional."
  },
  {
    Job_ID: "PING-PM-001",
    Priority: "B - Credible stretch",
    Status: "Researching",
    Company: "Ping Identity",
    Role_Title: "Product Manager - Identity for AI",
    Role_Family: "Technical Product Management / Identity / AI",
    Seniority: "Mid-level",
    Location: "Remote hiring across the UK",
    Country: "United Kingdom",
    Work_Model: "Remote or hybrid",
    Job_Link: "https://builtinedinburgh.uk/job/product-manager/9731093",
    Source: "Built In Edinburgh / Ping Identity",
    Date_Found: "2026-07-11",
    Application_Deadline: "Not stated",
    Salary: "Not stated",
    Visa_Sponsorship: "Not stated",
    Relocation_Support: "Not stated",
    Japanese_Requirement: "None",
    Key_Requirements: "Drive execution for an Identity for AI product; gather customer and market requirements; manage roadmap/backlog; produce technical requirements; support launch and go-to-market. Requires cloud experience, strong IAM/zero-trust and identity-standards knowledge, hands-on AI framework deployment, developer/admin products and zero-to-one delivery.",
    Match_Evidence: "Cloud migration leadership; software engineering and technical Product Owner experience; permissioned approval workflows; security-conscious regulated systems; requirements, releases and cross-functional collaboration; developer-facing technical fluency.",
    Skill_Gaps: "Strong IAM, OAuth/OIDC or zero-trust expertise is not demonstrated; no hands-on AI framework deployment at scale; limited zero-to-one market-facing product ownership and go-to-market enablement.",
    Match_Score_10: "7.0",
    Interest_Score_10: "8.5 - provisional",
    Visa_Feasibility_10: "7 - not stated",
    Urgency_Score_10: "7",
    Application_Effort_5: "5",
    Strategic_Score_100: "72",
    CV_Version: "Technical Product Manager / Cloud, Access & AI",
    Cover_Letter_Status: "Recommended",
    Referral_or_Contact: "",
    Networking_Status: "Find a UK product or identity-platform contact",
    Applied_Date: "",
    Follow_Up_Date: "",
    Interview_Stage: "",
    Next_Action: "Apply after higher-probability roles. Frame permissions, controls and cloud delivery as adjacent evidence, while explicitly presenting IAM and AI-framework depth as the learning edge.",
    Next_Action_Due: "2026-07-14",
    Outcome: "",
    Notes: "Mid-level title helps, but the identity and scaled-AI requirements are substantial screening risks."
  },
  {
    Job_ID: "CUJO-PM-001",
    Priority: "B - Targeted stretch",
    Status: "Researching",
    Company: "CUJO AI",
    Role_Title: "Product Manager, Device Intelligence",
    Role_Family: "Technical Product Management / AI / Networking",
    Seniority: "Senior",
    Location: "Remote-friendly; UK preferred, other European countries considered",
    Country: "United Kingdom / Europe",
    Work_Model: "Remote or hybrid",
    Job_Link: "https://builtinedinburgh.uk/job/product-manager-device-intelligence/9648829",
    Source: "Built In Edinburgh / CUJO AI",
    Date_Found: "2026-07-11",
    Application_Deadline: "2026-07-19; may close earlier",
    Salary: "Not stated",
    Visa_Sponsorship: "Not stated",
    Relocation_Support: "Not stated",
    Japanese_Requirement: "None",
    Key_Requirements: "Own roadmap and quarterly planning for a B2B Device Intelligence product; write PRDs and acceptance criteria; lead discovery, backlog and Agile ceremonies; coordinate Cloud, Firmware, Research and QA teams; engage tier-1 network providers; define AI/LLM workflows; strong device fingerprinting, network traffic, IoT protocol and data-analysis knowledge.",
    Match_Evidence: "Acting Product Owner and software engineer; PRDs/specifications, backlog, sprint planning and release delivery; B2B financial platforms; cloud migration; SQL and data analysis; technical stakeholder communication; experience translating operational needs into engineering work.",
    Skill_Gaps: "Core domain gaps in device intelligence, network traffic analysis, firmware, Wi-Fi/IoT protocols and ML product lifecycle. Limited strategic-customer and sales-enablement ownership.",
    Match_Score_10: "6.6",
    Interest_Score_10: "8 - provisional",
    Visa_Feasibility_10: "7 - not stated",
    Urgency_Score_10: "8",
    Application_Effort_5: "5",
    Strategic_Score_100: "67",
    CV_Version: "Technical Product Manager / Data & AI",
    Cover_Letter_Status: "Recommended; must address domain learning honestly",
    Referral_or_Contact: "jobs@cujo.com",
    Networking_Status: "Optional recruiter/product-team outreach",
    Applied_Date: "",
    Follow_Up_Date: "",
    Interview_Stage: "",
    Next_Action: "Apply only after the A-priority roles. Emphasise technical B2B product delivery, data quality, PRDs and cloud systems; do not imply networking or ML expertise you do not have.",
    Next_Action_Due: "2026-07-15",
    Outcome: "",
    Notes: "Attractive remote AI role, but several specialist domain requirements are central rather than decorative."
  }
];
